# Generated by Django 4.1.3 on 2022-11-30 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("borrowing", "0003_borrowing_check_borrow_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PE", "PENDING"), ("PA", "PAID")], max_length=7
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("PA", "PAYMENT"), ("FI", "FINE")], max_length=7
                    ),
                ),
                ("session_url", models.URLField()),
                ("session_id", models.CharField(max_length=255)),
                ("money", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "borrowing",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="borrowing.borrowing",
                    ),
                ),
            ],
        ),
    ]
