# Generated by Django 4.1.3 on 2022-11-30 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='status',
            new_name='status_payment',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='type',
            new_name='type_payment',
        ),
    ]
