# Generated by Django 4.1.3 on 2022-12-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_rename_status_payment_status_payment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="money",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
