# Generated by Django 4.1.3 on 2022-11-30 11:55

from django.db import migrations, models
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    dependencies = [
        ("borrowing", "0002_alter_borrowing_actual_return_date_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="borrowing",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("borrow_date__lte", django.db.models.functions.datetime.Now())
                ),
                name="check_borrow_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="borrowing",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("expected_date__gt", django.db.models.functions.datetime.Now())
                ),
                name="check_expected_return_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="borrowing",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "actual_return_date__gt",
                        django.db.models.functions.datetime.Now(),
                    )
                ),
                name="check_actual_return_date",
            ),
        ),
    ]
