# Generated by Django 4.1.3 on 2022-12-01 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0003_borrowing_check_borrow_date_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='borrowing',
            name='check_actual_return_date',
        ),
    ]
