# Generated by Django 4.1.3 on 2022-11-30 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_alter_book_daily_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="daily_fee",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
